language: node_js

node_js:  
  - "12"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/fruit

before_script:
  - psql -c 'create database fruit' -U postgres
  - psql -U postgres -d fruit -a -f table.sql

services:
  - postgresql